---
- name: Perform Git Pull
  become: false
  git:
    repo: git@github.com:AbuchiKings/aws_ec2_auto_deploy.git # Replace with github repo you prefer
    dest: ~/apps/aws_ec2_auto_deploy
    accept_hostkey: yes
    clone: false
    version: main # Replace with the desired branch or tag

- name: Install packages
  npm:
    path: ~/apps/aws_ec2_auto_deploy
    ci: true

- name: Run Docker build
  become: true
  shell: |
    cd ~/apps/aws_ec2_auto_deploy
    make down
    make up-d
