version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:16.17.0
      - image: cimg/redis:6.2.6
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: ${DB_PASS}
          MYSQL_DATABASE: ${DB_NAME}
          MYSQL_USER: ${DB_USER}
          MYSQL_PASSWORD: ${DB_PASS}
    steps:
      - checkout
      - restore_cache:
          keys: [packages]
      - run:
          name: Test MYSQL connection
          command: |
            for i in `seq 1 30`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1

      - run:
          name: Run tests
          command: |
            pwd
            mv .env.example .env
            ls -a
            npm install
            npm run migrate:latest

workflows:
  default:
    jobs:
      - test
